[package]
name = "watchgou"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2.93"
base64 = "0.22.1"
memchr = { version = "2", default-features = false }
